name: Build & Release APK

on:
  push:
    branches:
      - main
      - master
      - "*" # هذا السطر يضمن تشغيل البناء على أي فرع تقوم بالرفع عليه
  workflow_dispatch: # لتشغيل الزر يدوياً

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug --no-daemon

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AeroVPN-Debug-APK
          path: app/build/outputs/apk/debug/app-debug.apk
